import { useState } from "react";
import { useMutation, useQuery, useAction } from "convex/react";
import { api } from "../../convex/_generated/api";
import { Calculator, Save, Download, BarChart3, TrendingUp, GitCompare } from "lucide-react";
import { toast } from "sonner";

export function InvestmentInsights() {
  const [calculatorType, setCalculatorType] = useState("SIP");
  const [amount, setAmount] = useState(5000);
  const [duration, setDuration] = useState(60);
  const [rate, setRate] = useState(12);
  const [calculationName, setCalculationName] = useState("");
  const [showSaveModal, setShowSaveModal] = useState(false);
  const [selectedNotes, setSelectedNotes] = useState<string[]>([]);

  const savedCalculations = useQuery(api.investments.getInvestmentCalculations) || [];
  const saveCalculation = useMutation(api.investments.saveInvestmentCalculation);
  const generateInsights = useAction(api.investments.generateInvestmentInsights);

  const calculateMaturity = () => {
    let maturityAmount = 0;
    
    if (calculatorType === "FD") {
      // Fixed Deposit: P(1 + r/100)^t
      maturityAmount = amount * Math.pow(1 + rate / 100, duration / 12);
    } else if (calculatorType === "RD") {
      // Recurring Deposit: M = R * [(1 + i)^n - 1] / i
      const monthlyRate = rate / 100 / 12;
      maturityAmount = amount * ((Math.pow(1 + monthlyRate, duration) - 1) / monthlyRate);
    } else if (calculatorType === "SIP") {
      // SIP: M = P * [((1 + i)^n - 1) / i] * (1 + i)
      const monthlyRate = rate / 100 / 12;
      maturityAmount = amount * (((Math.pow(1 + monthlyRate, duration) - 1) / monthlyRate) * (1 + monthlyRate));
    } else {
      // Custom calculation
      const monthlyRate = rate / 100 / 12;
      maturityAmount = amount * Math.pow(1 + monthlyRate, duration);
    }
    
    return Math.round(maturityAmount);
  };

  const maturityAmount = calculateMaturity();
  const totalReturns = maturityAmount - (calculatorType === "FD" ? amount : amount * duration);

  const handleSaveCalculation = async () => {
    if (!calculationName.trim()) {
      toast.error("Please enter a name for this calculation");
      return;
    }

    try {
      const insights = await generateInsights({
        type: calculatorType,
        amount: calculatorType === "FD" ? amount : amount,
        duration,
        rate,
        maturityAmount,
      });

      const chartData = JSON.stringify({
        labels: Array.from({ length: duration }, (_, i) => `Month ${i + 1}`),
        invested: Array.from({ length: duration }, (_, i) => 
          calculatorType === "FD" ? amount : amount * (i + 1)
        ),
        returns: Array.from({ length: duration }, (_, i) => {
          const months = i + 1;
          if (calculatorType === "FD") {
            return amount * Math.pow(1 + rate / 100, months / 12);
          } else {
            const monthlyRate = rate / 100 / 12;
            return amount * (((Math.pow(1 + monthlyRate, months) - 1) / monthlyRate) * (1 + monthlyRate));
          }
        }),
      });

      await saveCalculation({
        name: calculationName,
        type: calculatorType,
        amount: calculatorType === "FD" ? amount : amount,
        duration,
        rate,
        maturityAmount,
        aiInsights: insights,
        chartData,
      });

      toast.success("Calculation saved successfully!");
      setShowSaveModal(false);
      setCalculationName("");
    } catch (error) {
      toast.error("Failed to save calculation");
    }
  };

  const handleNoteSelection = (noteId: string) => {
    setSelectedNotes(prev => 
      prev.includes(noteId) 
        ? prev.filter(id => id !== noteId)
        : [...prev, noteId]
    );
  };

  const downloadPDF = (calculation: any) => {
    // Simulate PDF download
    const content = `
Investment Analysis Report
========================

Investment Type: ${calculation.type}
Amount: ₹${calculation.amount.toLocaleString()}
Duration: ${calculation.duration} months
Rate: ${calculation.rate}%
Maturity Amount: ₹${calculation.maturityAmount.toLocaleString()}

AI Insights:
${calculation.aiInsights}

Generated by MoneyMind - ${new Date().toLocaleDateString()}
    `;
    
    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${calculation.name}-analysis.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
    
    toast.success("Report downloaded successfully!");
  };

  return (
    <div className="min-h-screen bg-gray-50 dark:bg-gray-900 p-4 md:p-8">
      <div className="max-w-7xl mx-auto">
        <div className="mb-8">
          <h1 className="text-3xl font-bold text-gray-900 dark:text-white mb-2">Investment Insights</h1>
          <p className="text-gray-600 dark:text-gray-300">Calculate and analyze your investment returns with AI-powered insights</p>
        </div>

        <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
          {/* Calculator */}
          <div className="lg:col-span-2">
            <div className="bg-white dark:bg-gray-800 rounded-2xl shadow-lg p-6">
              <div className="flex items-center space-x-2 mb-6">
                <Calculator className="w-6 h-6 text-green-600" />
                <h2 className="text-xl font-semibold text-gray-900 dark:text-white">Investment Calculator</h2>
              </div>

              {/* Calculator Type Selection */}
              <div className="grid grid-cols-4 gap-2 mb-6">
                {["FD", "RD", "SIP", "Custom"].map((type) => (
                  <button
                    key={type}
                    onClick={() => setCalculatorType(type)}
                    className={`p-3 rounded-xl text-sm font-medium transition-all ${
                      calculatorType === type
                        ? "bg-green-600 text-white"
                        : "bg-gray-100 dark:bg-gray-700 text-gray-700 dark:text-gray-300 hover:bg-gray-200 dark:hover:bg-gray-600"
                    }`}
                  >
                    {type}
                  </button>
                ))}
              </div>

              {/* Input Sliders */}
              <div className="space-y-6">
                <div>
                  <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
                    {calculatorType === "FD" ? "Principal Amount" : "Monthly Investment"}: ₹{amount.toLocaleString()}
                  </label>
                  <input
                    type="range"
                    min="1000"
                    max="100000"
                    step="1000"
                    value={amount}
                    onChange={(e) => setAmount(parseInt(e.target.value))}
                    className="w-full h-2 bg-gray-200 dark:bg-gray-700 rounded-lg appearance-none cursor-pointer slider"
                  />
                  <div className="flex justify-between text-xs text-gray-500 dark:text-gray-400 mt-1">
                    <span>₹1,000</span>
                    <span>₹1,00,000</span>
                  </div>
                </div>

                <div>
                  <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
                    Duration: {duration} months ({Math.round(duration / 12 * 10) / 10} years)
                  </label>
                  <input
                    type="range"
                    min="6"
                    max="360"
                    step="6"
                    value={duration}
                    onChange={(e) => setDuration(parseInt(e.target.value))}
                    className="w-full h-2 bg-gray-200 dark:bg-gray-700 rounded-lg appearance-none cursor-pointer slider"
                  />
                  <div className="flex justify-between text-xs text-gray-500 dark:text-gray-400 mt-1">
                    <span>6 months</span>
                    <span>30 years</span>
                  </div>
                </div>

                <div>
                  <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
                    Annual Interest Rate: {rate}%
                  </label>
                  <input
                    type="range"
                    min="1"
                    max="25"
                    step="0.5"
                    value={rate}
                    onChange={(e) => setRate(parseFloat(e.target.value))}
                    className="w-full h-2 bg-gray-200 dark:bg-gray-700 rounded-lg appearance-none cursor-pointer slider"
                  />
                  <div className="flex justify-between text-xs text-gray-500 dark:text-gray-400 mt-1">
                    <span>1%</span>
                    <span>25%</span>
                  </div>
                </div>
              </div>

              {/* Results */}
              <div className="mt-8 p-6 bg-gradient-to-br from-green-50 to-green-100 dark:from-green-900/30 dark:to-green-800/30 rounded-xl">
                <h3 className="text-lg font-semibold text-gray-900 dark:text-white mb-4">Investment Summary</h3>
                <div className="grid grid-cols-2 gap-4">
                  <div>
                    <p className="text-sm text-gray-600 dark:text-gray-400">Total Investment</p>
                    <p className="text-2xl font-bold text-gray-900 dark:text-white">
                      ₹{(calculatorType === "FD" ? amount : amount * duration).toLocaleString()}
                    </p>
                  </div>
                  <div>
                    <p className="text-sm text-gray-600 dark:text-gray-400">Maturity Amount</p>
                    <p className="text-2xl font-bold text-green-600">₹{maturityAmount.toLocaleString()}</p>
                  </div>
                  <div>
                    <p className="text-sm text-gray-600 dark:text-gray-400">Total Returns</p>
                    <p className="text-xl font-semibold text-green-600">₹{totalReturns.toLocaleString()}</p>
                  </div>
                  <div>
                    <p className="text-sm text-gray-600 dark:text-gray-400">Effective Annual Return</p>
                    <p className="text-xl font-semibold text-green-600">
                      {(((maturityAmount / (calculatorType === "FD" ? amount : amount * duration)) ** (12 / duration) - 1) * 100).toFixed(2)}%
                    </p>
                  </div>
                </div>

                <button
                  onClick={() => setShowSaveModal(true)}
                  className="mt-4 w-full bg-green-600 text-white py-3 rounded-xl font-medium hover:bg-green-700 transition-colors flex items-center justify-center space-x-2"
                >
                  <Save className="w-4 h-4" />
                  <span>Save Calculation</span>
                </button>
              </div>
            </div>
          </div>

          {/* Saved Calculations */}
          <div className="space-y-6">
            <div className="bg-white dark:bg-gray-800 rounded-2xl shadow-lg p-6">
              <div className="flex items-center justify-between mb-4">
                <h3 className="text-lg font-semibold text-gray-900 dark:text-white">Saved Notes</h3>
                {selectedNotes.length > 1 && (
                  <button className="bg-blue-600 text-white px-3 py-1 rounded-lg text-sm hover:bg-blue-700 transition-colors flex items-center space-x-1">
                    <GitCompare className="w-4 h-4" />
                    <span>Compare</span>
                  </button>
                )}
              </div>

              <div className="space-y-3 max-h-96 overflow-y-auto">
                {savedCalculations.map((calc) => (
                  <div
                    key={calc._id}
                    className={`p-4 border-2 rounded-xl cursor-pointer transition-all ${
                      selectedNotes.includes(calc._id)
                        ? "border-blue-500 bg-blue-50 dark:bg-blue-900/30"
                        : "border-gray-200 dark:border-gray-700 hover:border-gray-300 dark:hover:border-gray-600"
                    }`}
                    onClick={() => handleNoteSelection(calc._id)}
                  >
                    <div className="flex items-center justify-between mb-2">
                      <h4 className="font-medium text-gray-900 dark:text-white">{calc.name}</h4>
                      <span className="text-xs bg-green-100 dark:bg-green-900/30 text-green-700 dark:text-green-300 px-2 py-1 rounded">
                        {calc.type}
                      </span>
                    </div>
                    <p className="text-sm text-gray-600 dark:text-gray-400 mb-2">
                      ₹{calc.amount.toLocaleString()} → ₹{calc.maturityAmount.toLocaleString()}
                    </p>
                    <div className="flex items-center justify-between">
                      <span className="text-xs text-gray-500 dark:text-gray-400">
                        {calc.duration} months @ {calc.rate}%
                      </span>
                      <button
                        onClick={(e) => {
                          e.stopPropagation();
                          downloadPDF(calc);
                        }}
                        className="text-gray-400 hover:text-gray-600 dark:hover:text-gray-300"
                      >
                        <Download className="w-4 h-4" />
                      </button>
                    </div>
                  </div>
                ))}

                {savedCalculations.length === 0 && (
                  <div className="text-center py-8 text-gray-500 dark:text-gray-400">
                    <BarChart3 className="w-12 h-12 mx-auto mb-3 opacity-50" />
                    <p>No saved calculations yet</p>
                    <p className="text-sm">Save your first calculation to see it here</p>
                  </div>
                )}
              </div>
            </div>
          </div>
        </div>

        {/* Save Modal */}
        {showSaveModal && (
          <div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50 p-4">
            <div className="bg-white dark:bg-gray-800 rounded-2xl p-6 w-full max-w-md">
              <h3 className="text-lg font-semibold text-gray-900 dark:text-white mb-4">Save Calculation</h3>
              <input
                type="text"
                value={calculationName}
                onChange={(e) => setCalculationName(e.target.value)}
                placeholder="Enter a name for this calculation"
                className="w-full px-4 py-3 rounded-xl border border-gray-300 dark:border-gray-600 bg-white dark:bg-gray-700 text-gray-900 dark:text-white focus:ring-2 focus:ring-green-500 focus:border-transparent mb-4"
              />
              <div className="flex space-x-3">
                <button
                  onClick={() => setShowSaveModal(false)}
                  className="flex-1 px-4 py-2 border border-gray-300 dark:border-gray-600 text-gray-700 dark:text-gray-300 rounded-xl hover:bg-gray-50 dark:hover:bg-gray-700 transition-colors"
                >
                  Cancel
                </button>
                <button
                  onClick={handleSaveCalculation}
                  className="flex-1 px-4 py-2 bg-green-600 text-white rounded-xl hover:bg-green-700 transition-colors"
                >
                  Save
                </button>
              </div>
            </div>
          </div>
        )}
      </div>
    </div>
  );
}
